; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nrf52840dk_nrf52840]
platform = nordicnrf52
board = nrf52840_dk
framework = zephyr
board_build.zephyr.extra_configs =
    CONFIG_NETWORKING=y
    CONFIG_NET_L2_IEEE802154=y
    CONFIG_NET_L2_IEEE802154_SECURITY=n
    CONFIG_NET_IPV6=y
    CONFIG_NET_UDP=y
    CONFIG_NET_SOCKETS=y
    CONFIG_NET_SOCKETS_POSIX_NAMES=y
    CONFIG_IEEE802154_NRF5=y
    CONFIG_NET_6LO=y
    CONFIG_NET_CONFIG_SETTINGS=y
    CONFIG_NET_CONFIG_MY_IPV6_ADDR="2001:db8::1"
    CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"
    CONFIG_NET_CONFIG_IEEE802154_DEV_NAME="nrf52840_ieee802154"
    CONFIG_NET_CONFIG_IEEE802154_CHANNEL=26
    CONFIG_NET_CONFIG_IEEE802154_PAN_ID=0xABCD
    CONFIG_NET_CONFIG_IEEE802154_RADIO_TX_POWER=0
    CONFIG_LOG=y
    CONFIG_NET_LOG=y
    CONFIG_SERIAL=y
    CONFIG_UART_CONSOLE=y

    CONFIG_NET_CONFIG_LOG_LEVEL_DBG=y
    CONFIG_IEEE802154_LOG_LEVEL_DBG=y
    CONFIG_LOG_DEFAULT_LEVEL=4

    CONFIG_ENTROPY_NRF5=y
    CONFIG_ENTROPY_HAS_DRIVER=y