CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y

# Only allow one connection, which is to the central.
CONFIG_BT_MAX_CONN=1

CONFIG_BT_DEVICE_NAME="Scanner"
CONFIG_BT_SMP=n
CONFIG_BT_GATT_CLIENT=y
