CONFIG_BT=y
# TODO: Find out which parameters should be set for a network node.
#CONFIG_BT_OBSERVER=y
#CONFIG_BT_CENTRAL=y
#CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_DEVICE_NAME="Node"
CONFIG_BT_SMP=n
CONFIG_BT_DEBUG_LOG=y